[package]
name = "pretty-printing"
authors = ["Xi Xiao <tdxiaoxi2@gmail.com>"]
version = "0.0.4"
edition = "2021"
description = "A simple pretty print implementation"
license = "MIT OR Apache-2.0"

[dependencies]
typed-arena = "2.0.2"

[dev-dependencies]
serde_json = "1.0.132"
